/*!
 * tanguage framework source code
 * Date: 2015-09-04
 */
;
{
    display: (grid.show == true),
    hasBar: this.series.bar ? true : false,
    hasScatter: this.series.scatter ? true : false,
    instance: this,
    ctx: this.getLayer(grid.zIndex).getContext("2d"),
    width: style.width,
    height: style.height,
    top: style.top,
    left: style.left,
    padding: grid.padding,

    xAxisMax: xAxis.max,
    xAxisMin: xAxis.min,
    xAxisShow: (xAxis.show == true),
    xAxisLineShow: (xAxis.axisLine.show == true),
    xAxisLineWidth: xAxis.axisLine.lineStyle.width,
    xAxisLineColor: xAxis.axisLine.lineStyle.color,

    xSplitLineShow: (xAxis.splitLine.show == true),
    xSplitLineWidth: xAxis.splitLine.lineStyle.width,
    xSplitLineColor: xAxis.splitLine.lineStyle.color,

    xLabelsShow: (xAxis.axisLabel.show == true),
    xLabelFontColor: xAxis.axisLabel.textStyle.fontColor,
    xLabelFontSize: xAxis.axisLabel.textStyle.fontSize,
    xLabelFontStyle: xAxis.axisLabel.textStyle.fontStyle,
    xLabelFontFamily: xAxis.axisLabel.textStyle.fontFamily,

    xLabels: xAxis.data,
    xTemplateString: xAxis.axisLabel.formatter,
    xOnZero: xAxis.axisLine.onZero,
    xBeginAtZero: (xAxis.axisLine.beginAtZero == true),
    xIntegersOnly: true,

    yAxisMax: yAxis.max,
    yAxisMin: yAxis.min,
    yAxisShow: (yAxis.show == true),
    yAxisLineShow: (yAxis.axisLine.show == true),
    yAxisLineWidth: yAxis.axisLine.lineStyle.width,
    yAxisLineColor: yAxis.axisLine.lineStyle.color,

    ySplitLineShow: (yAxis.splitLine.show == true),
    ySplitLineWidth: yAxis.splitLine.lineStyle.width,
    ySplitLineColor: yAxis.splitLine.lineStyle.color,

    yLabelsShow: (yAxis.axisLabel.show == true),
    yLabelFontColor: yAxis.axisLabel.textStyle.fontColor,
    yLabelFontSize: yAxis.axisLabel.textStyle.fontSize,
    yLabelFontStyle: yAxis.axisLabel.textStyle.fontStyle,
    yLabelFontFamily: yAxis.axisLabel.textStyle.fontFamily,

    yLabels: yAxis.data,
    yTemplateString: yAxis.axisLabel.formatter,
    yOnZero: yAxis.axisLine.onZero,
    yBeginAtZero: (yAxis.axisLine.beginAtZero == true),
    yIntegersOnly: true
}