/*!
 * tanguage framework source code
 *
 * class draw/Charts
 *
 * Date: 2015-09-04
 */
;
{
    show: true,
    type: 'label',
    axisLine: {
        show: true,
        onZero: false,
        lineStyle: {
            color: "rgba(0,0,0,.2)",
            width: 1
        }
    },
    splitLine: {
        show: true,
        lineStyle: {
            color: "rgba(0,0,0,.05)",
            width: 1
        }
    },
    axisLabel: {
        show: true,
        //inside: false,
        //rotate: 0,
        //margin: 8,
        formatter: "<%=value%>",
        textStyle: {
            fontFamily: "'Microsoft YaHei', 'Hiragino Sans'",
            fontSize: 12,
            fontStyle: "normal",
            fontColor: "#666"
        }
    },
    max: null,
    min: null,
    data: null
}