/*!
 * tanguage framework source code
 *
 * class draw/Charts
 *
 * Date: 2015-09-04
 */
;
{
    name: '',
    zIndex: 0,
    itemStyle: {
        normal: {
            color: null,
            barBorderColor: '#000',
            barBorderWidth: 0
        },
        emphasis: {
            color: null,
            barBorderColor: '#000',
            barBorderWidth: 0
        },
    },
    barWidth: 'auto',
    barMaxWidth: 'auto',
    barGap: 5,
    barCategoryGap: 3,
    data: []
}